# Generated by Django 4.0.1 on 2022-01-23 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_rename_name_user_full_name_user_email_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_time', models.DateTimeField(unique=True)),
                ('userid', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to='agency.user')),
            ],
        ),
    ]
