# Generated by Django 4.0.1 on 2022-01-23 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_remove_user_id_user_date_alter_user_email_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='schedule_time',
            new_name='schedule_time_from',
        ),
        migrations.AddField(
            model_name='interview',
            name='schedule_time_to',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
