# Generated by Django 4.0.1 on 2022-01-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_rename_schedule_time_interview_schedule_time_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to='agency.user')),
            ],
        ),
    ]
